version: "3.8"

services:
  app:
    container_name: task-crud-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      jaeger:
        condition: service_started
      kafka:
        condition: service_healthy
    env_file:
      - .env
    restart: always
    user: root
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/readiness"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  db:
    container_name: postgres-db
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgre
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  redis:
    container_name: redis-server
    image: redis:7
    command: ["redis-server", "--port", "6380", "--requirepass", "secret123"]
    ports:
      - "6380:6380"
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "-p", "6380", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.49
    ports:
      - "16686:16686"   # Web UI
      - "6831:6831/udp" # UDP collector
    networks:
      - app-network
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411

  zookeeper:
    container_name: zookeeper
    image: bitnami/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "nc -zv zookeeper 2181"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  kafka:
    container_name: kafka
    image: bitnami/kafka:3.5
    depends_on:
      zookeeper:
        condition: service_healthy
    ports:
      - "9092:9092"
    networks:
      - app-network
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CFG_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server kafka:9092 --list || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    environment:
      KAFKA_CLUSTERS_0_NAME: "local"
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: "kafka:9092"
    ports:
      - "8081:8080"
    networks:
      - app-network
    depends_on:
      kafka:
        condition: service_healthy
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
